language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
branches:
  only:
    - master
node_js:
  - '9'
#   - '8'
#   - '6'
#   - '4'
script:
  - npm run cover
  - npm run check-coverage
  # - npm run build
after_success:
  # - npm run travis-deploy-once "npm run semantic-release"
  - npm run report-coverage
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
